# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

require 'google/protobuf'


descriptor_data = "\n\nauth.proto\x12\x08Protobuf\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"?\n\x0eVerifyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1c\n\x04user\x18\x02 \x01(\x0b\x32\x0e.Protobuf.User\"!\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t2C\n\x04\x41uth\x12;\n\x06Verify\x12\x17.Protobuf.VerifyRequest\x1a\x18.Protobuf.VerifyResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError => e
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Protobuf
  VerifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Protobuf.VerifyRequest").msgclass
  VerifyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Protobuf.VerifyResponse").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Protobuf.User").msgclass
end
