# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: auth.proto for package 'Protobuf'

require 'grpc'
require 'auth_pb'

module Protobuf
  module Auth
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Protobuf.Auth'

      rpc :Verify, ::Protobuf::VerifyRequest, ::Protobuf::VerifyResponse
    end

    Stub = Service.rpc_stub_class
  end
end
