name: Athena pipeline

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RACK_ENV: test
      DATABASE_USR: athena
      DATABASE_PASSWORD: athena
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: athena
          POSTGRES_PASSWORD: athena
          POSTGRES_DB: athena_backend_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: install bundler
        run: gem install bundler
      - name: install dependencies
        run: bundle install
      - name: Wait for Database
        run: |
          while ! nc -z localhost 5432; do
            echo "Waiting for PostgreSQL to start..."
            sleep 1
          done
          echo "PostgreSQL is up and running."
      - name: Create Test Database
        run: bundle exec rails db:create RAILS_ENV=test
      - name: Run RSpec Tests
        run: bundle exec rspec
