name: Athena pipeline

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RACK_ENV: test
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: athena_backend_test
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: install bundler
        run: gem install bundler
      - name: install dependencies
        run: bundle install
      - name: show env
        run: |
          echo $DATABASE_USR
          echo $DATABASE_PASSWORD
          echo $DATABASE_HOST
          echo $DATABASE_PORT
          sudo apt-get -yqq install libpq-dev
      - name: test connection
        run: RAILS_ENV=test bundle exec rails db:migrate
        env:
          DATABASE_USR: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
#      - name: Create Test Database
#        run: bundle exec rails db:migrate RAILS_ENV=test
#      - name: Run RSpec Tests
#        run: bundle exec rspec
